version: "3"
services:
  crewsnet:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./config.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prakhar
      - MONGO_INITDB_ROOT_PASSWORD=prakhar
